contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bovisanalyzer channel"
    url: https://nfcore.slack.com/channels/bovisanalyzer
    about: Discussion about the nf-core/bovisanalyzer pipeline
